第一版测试
Moonshile/seedup pull request #1
Opened 2018-09-12 14:24 UTC by oslele

第一版简单的实现了网页下载，网页分析，还存在很多bug，比较low

2018-09-13 11:45 UTC, Moonshile requested changes
可以先根据这些comments纠正一下。另外请思考如何重构。

2018-09-13 11:45 UTC, Moonshile commented on result.csv
> +�Ѽ� �� �������ر���3����-������,[����Ӫ] 6���߲ݷ�,8.8 �O,3/13��,3��1��,��6���߲ݷ�վ332��,������|���幩ů|�Ѽ�3.0 ľ��|�Ѽ�3.0 ľ��
不做说明时一般使用UTF8

2018-09-13 11:45 UTC, Moonshile commented on test.py
> +import urllib
#coding=utf-8

2018-09-13 11:45 UTC, Moonshile commented on test.py
> +#request任务队列
尽量使用英文注释、说明，除非是做界面并且只支持汉语使用者

2018-09-13 11:45 UTC, Moonshile commented on test.py
> +def parseHtml(str): #解析获取的html文件并将结果写入文件
使用python的文档型注释

2018-09-13 11:45 UTC, Moonshile commented on test.py
> +    soup=BeautifulSoup(open(str,encoding='UTF-8'),'lxml')
一般情况下运算符左右需要空格

2018-09-13 11:45 UTC, Moonshile commented on test.py
> +    #print(soup.find('ul',id='houseList'))
提交的代码必须是干净的，不需要的code应该删掉。
如果需要保留调试信息，可以使用log系统。

2018-09-13 11:45 UTC, Moonshile commented on test.py
> +
空一行即可

2018-09-15 02:09 UTC, Moonshile commented
> 第一版简单的实现了网页下载，网页分析，还存在很多bug，比较low

嗯，认识到自己的缺点很不错，不过还需要
1. 认识自己的收获
2. 认识到缺点后，给出改进方案

2018-09-19 14:28 UTC, oslele commented on test.py
> +    soup=BeautifulSoup(open(str,encoding='UTF-8'),'lxml')
嗯，原来我习惯性的都会加空格的，但是看有些网站的例子没有写，我专门改了。。。。

2018-09-19 14:28 UTC, oslele commented on test.py
> +def parseHtml(str): #解析获取的html文件并将结果写入文件
get

2018-09-19 14:29 UTC, oslele commented on test.py
> +#request任务队列
大哥，英语不太好怎么办。。。拼音行么？

2018-09-22 01:47 UTC, Moonshile commented on test.py
> +#request任务队列
那就先用中文吧，不过必须开始阅读英文文档

2019-07-24 06:53 UTC, closed without merging